default_stages: [commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - "--args=--lockfile=false"
          - --hook-config=--path-to-file=README.md       
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_tflint

  - repo: https://github.com/compilerla/conventional-pre-commit.git
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [
            feat,
            feat!,
            fix,
            build,
            chore,
            ci,
            docs,
            perf,
            refactor,
            revert,
            style,
            wip,
            BREAKING CHANGE,
            test
          ] # optional: list of Conventional Commits types to allow